### PR TITLE
Test binary io compression modes

### PR DESCRIPTION
**Pull request by DavyLandman**
As discussed in #245 we were lacking tests for this. This PR introduces tests, and also fixes 2 bugs that prevented the different compression modes from working.

### CODE REVIEW

**Comment by jurgenvinju** [comment]
nice! did we check at least once that files written with the old writer can be read in with the new reader? I don't propose we add an automated test for this, but at least once let's test this because when we release one bit of difference could lead to dozens of emails from users. 

[eandf.dra.zip](https://github.com/usethesource/vallang/files/14446451/eandf.dra.zip)

I think a single file would be enough to find any possible bit-level differences between the old and the new implementation. 

The zipped file is a binary value file written with 0.34.0 of Rascal using `ValueIO::writeBinaryValueFile` no compression options where supplied.

**Comment by jurgenvinju** [comment]
As I understood it the binary reader _creates_ a TypeStore while reading the definitions in the binary file. It does not require the declarations up front.

**Comment by DavyLandman** [comment]
I couldn't get it to work (reading that file in vallang). If you think that is an important test-case to add, please feel free to extend this PR. I don't have time the coming days to debug that.

**Comment by jurgenvinju** [comment]
I'll try to use this PR SNAPSHOT in Rascal to test the backward compatibility...

```
rascal>readBinaryValueFile(|home:///pico.dra|)
value: model(
  type(
    sort("Expression"),
    (
      empty():choice(
        empty(),
        {prod(
            empty(),
            [],
            {})}),
      sort("Type"):choice(
        sort("Type"),

```

this works for all binary value files `find` could find in my home folder.

**Pull request merged**
